@startuml
hide empty description

' Define the states
[*] --> START

START --> QUOTE_0 : SCM_QUOTE
START --> QUASIQUOTE_0 : SCM_QUASIQUOTE
START --> LP_A : SCM_LPAREN
START --> RP_A : SCM_RPAREN
START --> IDENTIFIER_0 : SCM_IDENTIFIERS_BASE
START --> LITERAL_NUMBER_0 : SCM_NUMBERS
START --> LITERAL_STRING_0 : SCM_QUOTATION
START --> LITERAL_BOOLEAN_0 : SCM_HASHTAG

QUOTE_0 --> QUOTE_A : SCM_LETTERS_NUMBERS
QUASIQUOTE_0 --> QUASIQUOTE_A : SCM_LETTERS_NUMBERS

IDENTIFIER_0 --> IDENTIFIER_0 : SCM_IDENTIFIERS_ALL
LITERAL_NUMBER_0 --> IDENTIFIER_0 : SCM_LETTERS
LITERAL_NUMBER_0 --> LITERAL_NUMBER_0 : SCM_NUMBERS
LITERAL_NUMBER_0 --> LITERAL_NUMBER_A : ε
LITERAL_STRING_0 --> INVALID_R : SCM_EOS
LITERAL_STRING_0 --> LITERAL_STRING_0 : SCM_LITERAL_STRING
LITERAL_STRING_0 --> LITERAL_STRING_1 : SCM_LITERAL_STRING_ESCAPE
LITERAL_STRING_0 --> LITERAL_STRING_A : SCM_QUOTATION
LITERAL_STRING_1 --> LITERAL_STRING_0 : SCM_LITERAL_STRING_VALID_ESCAPED
LITERAL_BOOLEAN_0 --> LITERAL_BOOLEAN_1 : SCM_BOOLEAN_CHARS

QUOTE_A --> [*] : Accept
QUASIQUOTE_A --> [*] : Accept

LP_A --> [*] : Accept
RP_A --> [*] : Accept

LITERAL_NUMBER_A --> [*] : Accept
LITERAL_STRING_A --> [*] : Accept

@enduml
